BUNDLE_NAME = prefs
prefs_FILES = PKBRootListController.m
$(BUNDLE_NAME)_PRIVATE_FRAMEWORKS = Preferences
$(BUNDLE_NAME)_EXTRA_FRAMEWORKS = Cephei CepheiPrefs


include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
